USE banking;

insert into `Bank`(`cId`,`cCode`,`cName`) values (1,'246','Banco ABC Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (2,'025','Banco Alfa S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (3,'641','Banco Alvorada S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (4,'029','Banco Banerj S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (5,'000','Banco Bankpar S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (6,'740','Banco Barclays S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (7,'107','Banco BBM S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (8,'031','Banco Beg S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (9,'739','Banco BGN S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (10,'096','Banco BM&F de Servicos de Liquidacao e Custodia S.A');
insert into `Bank`(`cId`,`cCode`,`cName`) values (11,'318','Banco BMG S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (12,'752','Banco BNP Paribas Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (13,'248','Banco Boavista Interatlantico S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (14,'218','Banco Bonsucesso S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (15,'065','Banco Bracce S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (16,'036','Banco Bradesco BBI S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (17,'204','Banco Bradesco Cartoes S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (18,'394','Banco Bradesco Financiamentos S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (19,'237','Banco Bradesco S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (20,'225','Banco Brascan S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (21,'208','Banco BTG Pactual S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (22,'044','Banco BVA S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (23,'263','Banco Cacique S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (24,'473','Banco Caixa Geral - Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (25,'040','Banco Cargill S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (26,'233','Banco Cifra S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (27,'745','Banco CitiBank S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (28,'M08','Banco Citicard S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (29,'M19','Banco CNH Capital S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (30,'215','Banco Comercial e de Investimento Sudameris S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (31,'756','Banco Cooperativo do Brasil S.A. - BANCOOB');
insert into `Bank`(`cId`,`cCode`,`cName`) values (32,'748','Banco Cooperativo Sicredi S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (33,'222','Banco Credit Agricole Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (34,'505','Banco Credit Suisse (Brasil) S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (35,'229','Banco Cruzeiro do Sul S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (36,null,'Banco CSF S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (37,'003','Banco da Amazonia S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (38,'083-3','Banco da China Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (39,'707','Banco Daycoval S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (40,'M06','Banco de Lage Landen Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (41,'024','Banco de Pernambuco S.A. - BANDEPE');
insert into `Bank`(`cId`,`cCode`,`cName`) values (42,'456','Banco de Tokyo-Mitsubishi UFJ Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (43,'214','Banco Dibens S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (44,'001','Banco do Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (45,'047','Banco do Estado de Sergipe S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (46,'037','Banco do Estado do Para S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (47,'041','Banco do Estado do Rio Grande do Sul S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (48,'004','Banco do Nordeste do Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (49,'265','Banco Fator S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (50,'M03','Banco Fiat S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (51,'224','Banco Fibra S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (52,'626','Banco Ficsa S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (53,null,'Banco Fidis S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (54,'394','Banco Finasa BMC S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (55,'M18','Banco Ford S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (56,'M07','Banco GMAC S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (57,'612','Banco Guanabara S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (58,'M22','Banco Honda S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (59,'063','Banco Ibi S.A. Banco Multiplo');
insert into `Bank`(`cId`,`cCode`,`cName`) values (60,'M11','Banco IBM S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (61,'604','Banco Industrial do Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (62,'320','Banco Industrial e Comercial S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (63,'653','Banco Indusval S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (64,'249','Banco Investcred Unibanco S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (65,'184','Banco Itau BBA S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (66,'479','Banco ItauBank S.A');
insert into `Bank`(`cId`,`cCode`,`cName`) values (67,null,'Banco Itaucard S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (68,'M09','Banco Itaucred Financiamentos S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (69,'376','Banco J. P. Morgan S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (70,'074','Banco J. Safra S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (71,'217','Banco John Deere S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (72,'600','Banco Luso Brasileiro S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (73,'389','Banco Mercantil do Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (74,'746','Banco Modal S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (75,'045','Banco Opportunity S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (76,'079','Banco Original do Agronegocio S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (77,'623','Banco Panamericano S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (78,'611','Banco Paulista S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (79,'643','Banco Pine S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (80,'638','Banco Prosper S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (81,'747','Banco RaboBank International Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (82,'356','Banco Real S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (83,'633','Banco Rendimento S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (84,'M16','Banco Rodobens S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (85,'072','Banco Rural Mais S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (86,'453','Banco Rural S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (87,'422','Banco Safra S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (88,'033','Banco Santander (Brasil) S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (89,'749','Banco Simples S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (90,'366','Banco Sociot  G n rale Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (91,'637','Banco Sofisa S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (92,'012','Banco Standard de Investimentos S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (93,'464','Banco Sumitomo Mitsui Brasileiro S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (94,'082-5','Banco Topazio S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (95,'M20','Banco Toyota do Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (96,'634','Banco Triangulo S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (97,'M14','Banco Volkswagen S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (98,'M23','Banco Volvo (Brasil) S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (99,'655','Banco Votorantim S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (100,'610','Banco VR S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (101,'119','Banco Western Union do Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (102,'370','Banco WestLB do Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (103,null,'Banco Yamaha Motor S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (104,'021','BANESTES S.A. Banco do Estado do Espirito Santo');
insert into `Bank`(`cId`,`cCode`,`cName`) values (105,'719','Banif-Banco Internacional do Funchal (Brasil)S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (106,'755','Bank of America Merrill Lynch Banco Multiplo S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (107,'073','BB Banco Popular do Brasil S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (108,'250','BCV - Banco de Credito e Varejo S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (109,'078','BES Investimento do Brasil S.A.-Banco de Investimento');
insert into `Bank`(`cId`,`cCode`,`cName`) values (110,'069','BPN Brasil Banco Multiplo S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (111,'070','BRB - Banco de Brasilia S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (112,'104','Caixa Economica Federal');
insert into `Bank`(`cId`,`cCode`,`cName`) values (113,'477','CitiBank S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (114,'081-7','Concordia Banco S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (115,'487','Deutsche Bank S.A. - Banco Alemao');
insert into `Bank`(`cId`,`cCode`,`cName`) values (116,'064','Goldman Sachs do Brasil Banco Multiplo S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (117,'062','Hipercard Banco Multiplo S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (118,'399','HSBC Bank Brasil S.A. - Banco Multiplo');
insert into `Bank`(`cId`,`cCode`,`cName`) values (119,'492','ING Bank N.V.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (120,'652','Itau Unibanco Holding S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (121,'341','Itau Unibanco S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (122,'488','JPMorgan Chase Bank');
insert into `Bank`(`cId`,`cCode`,`cName`) values (123,'751','ScotiaBank Brasil S.A. Banco Multiplo');
insert into `Bank`(`cId`,`cCode`,`cName`) values (124,null,'Standard Chartered Bank (Brasil) S/A Bco Invest.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (125,'409','UNIBANCO - Uniao de Bancos Brasileiros S.A.');
insert into `Bank`(`cId`,`cCode`,`cName`) values (126,'230','Unicard Banco Multiplo S.A.');
